[build]
target = "thumbv7em-none-eabihf"
rustflags = [
  "-C", "link-arg=--script=link.ld",
  "-C", "link-arg=--emit-relocs",
  "-C", "relocation-model=ropi-rwpi",
  "--emit", "asm",
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
